name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Check if secrets are available
      - name: Test Secrets Output
        run: |
          echo "Registry Username: ${{ secrets.REGISTRY_USERNAME }}"
          echo "Registry Password is set: $([[ -n '${{ secrets.REGISTRY_PASSWORD }}' ]] && echo 'Yes' || echo 'No')"

      # Docker login step
      - uses: azure/docker-login@v2
        with:
          login-server: registry01poland.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t flask_app:${{ github.sha }} .
          docker tag flask_app:${{ github.sha }} registry01poland.azurecr.io/flask_app:${{ github.sha }}
          docker push registry01poland.azurecr.io/flask_app:${{ github.sha }}
